[package]
name = "ff4"
version = "0.1.0"
authors = ["Jason Lynch <jason@calindora.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
image = "0.23.7"
sha2 = "0.9.1"
